bug #32 closes , correct bug number done
fossasia/meilix-systemlock pull request #36
Opened 2018-12-26 15:30 UTC by Manas-kashyap

Fixes #32 
Checklist
I have read the Contribution & Best practices Guide and my PR follows them.
My branch is up-to-date with the Upstream master branch.
I have added necessary documentation (if appropriate)
Added brief description
Changes proposed in this pull request:
Change done in debian/changelog resolving bug number 

Thank you!

2018-12-26 15:34 UTC, pranav1698 requested changes
@Manas-kashyap This pr should contain changes only for the issue #32 
Not for the other pr

2018-12-26 15:57 UTC, pranav1698 approved these changes
LGTM!

2018-12-27 19:59 UTC, tabesin requested changes
Pls rebase

2019-01-03 15:47 UTC, pranav1698 requested changes

2019-01-03 15:47 UTC, pranav1698 commented on systemlock-0.1/debian/changelog
> +systemlock (0.1-1) unstable; urgency=low
Delete this file

2019-01-03 15:50 UTC, Manas-kashyap commented on systemlock-0.1/debian/changelog
> +systemlock (0.1-1) unstable; urgency=low
Done

2019-01-03 15:54 UTC, pranav1698 approved these changes

2019-01-03 17:18 UTC, tabesin approved these changes

2019-01-03 17:18 UTC, merged